INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('FAEX', 'ARAGON');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('FIREFOX', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('BILI', 'SORIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EXTARSA', 'ARAGON');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('FIRE ICE', 'SALAMANCA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('T. EXTINTOR', 'MADRID');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EXMON', 'NAVARRA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EXTINCISE', 'BARCELONA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('COINTRA', 'C. MANCHA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('SEISA', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('VALLE UNION', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('MAGNUM', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('ELITEX', 'MADRID');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('ACTION FIRE', 'SALAMANCA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('FARIVAL', 'MADRID');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('ALERTA', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('AUCA', 'VALENCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('TECNO ENVASE', 'C. MANCHA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('GRUPO INCENDIOS', 'SORIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('ZENITH', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('GAMA', 'PAÍS VASCO');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('UNIVERSAL', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('MICROPRESS', 'BARCELONA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EXFAEX', 'ARAGON');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('MACOIN', 'SORIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('GLORIA', 'MURCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('MONCAYO', 'NAVARRA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('MONTOYA', 'MADRID');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('PARSI', 'BARCELONA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EXTIN SPARST', 'MADRID');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('FIREPOWER', 'LONDRES');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EIVAR', 'VALENCIA');
INSERT INTO ref_provedores_extintores (marca, provincia) VALUES ('EXTINPRES', 'MADRID');
